spring:
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}:9092
      acks: all

      properties:
        enable.idempotence: true
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}:9092
      group-id: scheduler-group
      trusted-packages: com.kafka.rpc.summarization

internal:
  service.secret: ${INTERNAL_SERVICE_SECRET}

server:
  port: 8082